"""add post_id field in post photo

Revision ID: 0e534fd05b7d
Revises: 3d8b74f8d119
Create Date: 2025-05-06 11:11:12.983449

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e534fd05b7d'
down_revision: Union[str, None] = '3d8b74f8d119'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post_photo', sa.Column('post_id', sa.BigInteger(), nullable=False))
    op.create_index(op.f('ix_post_photo_post_id'), 'post_photo', ['post_id'], unique=False)
    op.create_foreign_key(None, 'post_photo', 'post', ['post_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_photo', type_='foreignkey')
    op.drop_index(op.f('ix_post_photo_post_id'), table_name='post_photo')
    op.drop_column('post_photo', 'post_id')
    # ### end Alembic commands ###
