"""add owner in group

Revision ID: 635392773fbb
Revises: 60b4eff8d7c7
Create Date: 2025-05-06 05:42:27.732096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '635392773fbb'
down_revision: Union[str, None] = '60b4eff8d7c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('group', sa.Column('group_owner_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'group', 'user', ['group_owner_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'group', type_='foreignkey')
    op.drop_column('group', 'group_owner_id')
    # ### end Alembic commands ###
